#
# Application files
#
rootdir: /home/ikuchin/src
subfolders: [dev.connme.ru, dev.bestbounty.ru, dev.infomed-stat.ru, dev.timecard.ru]
files:
  - .github/actions/linters/.eslintrc.yaml
  - .github/actions/release-drafter/release-drafter.yml
  - .github/actions/spelling/only.txt
  - .github/workflows/qa.yml
  - .github/workflows/release-deployment.yml
  - .github/workflows/release-drafter.yml
  - .github/workflows/sast.yml
  - .github/workflows/spell_check.yml
  - .github/workflows/super_linter.yml
  - .gitignore
  - CMakeLists.txt
  - CMakeModules/FindLibArchive.cmake
  - CMakeModules/FindLibAVCodec.cmake
  - CMakeModules/FindLibAVFormat.cmake
  - CMakeModules/FindLibAVUtil.cmake
  - CMakeModules/FindLibHPDF.cmake
  - CMakeModules/FindLibImageMagick.cmake
  - CMakeModules/FindLibMaxMindDB.cmake
  - CMakeModules/FindLibRapidJSON.cmake
  - CMakeModules/FindLibSSL.cmake
  - CMakeModules/FindLibSwScale.cmake
  - CMakeModules/FindLibWebSockets.cmake
  - CMakeModules/FindLibWkhtmlToX.cmake
  - CMakeModules/FindLibXL.cmake
  - CMakeModules/FindLibZ.cmake
  - po/CMakeLists.txt
  - src/pd/system.cpp
  - supplemental/apache2/conf-available/mod_expires.conf
  - supplemental/apache2/sites-available/099-images.conf
  - supplemental/apache2/sites-available/099-www.conf
  - supplemental/config/CMakeLists.txt
  - supplemental/cron/CMakeLists.txt
  - supplemental/cron/cron_config.in
  - supplemental/docker/prod/Dockerfile
  - supplemental/docker/qa/Dockerfile
  - supplemental/git/CMakeLists.txt
  #- supplemental/git/git_commit_id
  - supplemental/libpdf-font/CMakeLists.txt
  - supplemental/maxmind/CMakeLists.txt
  #- supplemental/ssmtp/CMakeLists.txt
  #- supplemental/ssmtp/ssmtp.conf.in
  - templates/CMakeLists.txt
  - templates/ru/mails/prod/activator_regNewUser.htmlt
  - templates/ru/mails/prod/change_email.htmlt
  - templates/ru/mails/prod/forget.htmlt
  - templates/ru/mails/prod/helpdesk_notification_existing_case.htmlt
  - templates/ru/mails/prod/helpdesk_notification_new_case.htmlt
  - templates/ru/pages/prod/activator_regNewUser.htmlt
  - templates/ru/pages/prod/autologin.htmlt
  - templates/ru/pages/prod/cases_list.htmlt
  - templates/ru/pages/prod/cookie_policy.htmlt
  - templates/ru/pages/prod/cookie_policy_wrapper.htmlt
  - templates/ru/pages/prod/create_password_block.htmlt
  - templates/ru/pages/prod/email_change.htmlt
  - templates/ru/pages/prod/error.htmlt
  - templates/ru/pages/prod/eula.htmlt
  - templates/ru/pages/prod/eula_wrapper.htmlt
  - templates/ru/pages/prod/faq.htmlt
  - templates/ru/pages/prod/forget_password.htmlt
  - templates/ru/pages/prod/guest_navigation_menu.htmlt
  - templates/ru/pages/prod/helpdesk_dashboard.htmlt
  - templates/ru/pages/prod/helpdesk_navigation_menu.htmlt
  - templates/ru/pages/prod/login_header.htmlt
  - templates/ru/pages/prod/navigation_menu_profile.htmlt
  - templates/ru/pages/prod/password_recovery.htmlt
  - templates/ru/pages/prod/privacy_policy.htmlt
  - templates/ru/pages/prod/privacy_policy_wrapper.htmlt
  - templates/ru/pages/prod/sms_confirmation.htmlt
  - templates/ru/pages/prod/user_account_properties.htmlt
  - templates/ru/pages/prod/user_notifications.htmlt
  - templates/ru/pages/prod/view_case.htmlt
  - templates/ru/pages/prod/weberror_cookie.htmlt
  - templates/us/pages/prod/error.htmlt
  - templates/us/pages/prod/index.htmlt
  - templates/us/pages/prod/json_response.htmlt
  - tests/auto/autotest_c_price_spelling.cpp
